### ISSUE TITLE
Research current APIs

### ISSUE THREAD

**Issue by el-g0m3z** [scottcm73/Pan-Tree#25]
There are some weird results being returned with the API, nasal spray 411 calories, kitty litter, etc.

Find out whats going on and see if we can get the data cleaned up.

**Comment by el-g0m3z** [comment]
Cesar, what are the limits on the API calls for free, vs subscription. Let us know if needed.

**Comment by techcheese** [comment]
I think we got the API figured out, Edamam is pretty powerful tool we will be using for our data extraction. and incorporate into some UI/UX features
